### ISSUE TITLE
体验优化

### ISSUE THREAD

**Issue by axing0223** [YILING0013/xianyun_Nai3GenIMG#1]
1.截取重绘中，使用图像生成时可以将生成的【小图】图像与【原图】图像合并到【图像输出】列表中。

2.使用截取重绘时，width和height被强制设置为1比1。（真会忘）

3.【图像输出】列表中，给当前显示的图像新增选中边框。（不知道当前选什么啊）

4.生成按钮添加打断功能。（要不然按了生成10次就真得硬等或者刷新了）

5.使用局部重绘功能时，无视smea设置

**Comment by axing0223** [comment]
6.把笔刷大小的上限增大大大大大大大一些。。

**Comment by YILING0013** [comment]
调整完成
