### ISSUE TITLE
图像输出队列的图片大小

### ISSUE THREAD

**Issue by axing0223** [YILING0013/xianyun_Nai3GenIMG#2]
固定队列框大小....不要根据队列的数量,种子的长度而变化.....
批量delete的时候真的很容易因为框体大小变化而点不到.

**Comment by axing0223** [comment]
在【delete】时，如果【delete】的是【当前图片】。
那么应该将【当前图片】调整为下一个图片。
（目前是保留当前图片不变）
这样的话。方便一遍快速预览一些不合格的图片，一边删一边看。
（目前就是删一个，点击切换图片，再删一个，就很麻烦。这样改完之后就可以一边删一边看了）

如果【delete】的不是【当前图片】。
那么不做任何处理即可。

**Comment by YILING0013** [comment]
“在【delete】时，如果【delete】的是【当前图片】。那么应该将【当前图片】调整为下一个图片。”
该问题已经修复，第一个“固定队列框大小.，不要根据队列的数量,种子的长度而变化”问题是由于在容器内元素超过限制长度后，会生成滚动条，占用一部分容器区域导致的自适应，不易去控制，此处不进行过多修改
